<font color='yellow'><h1>Libraries in python</h1></font>

•numpy
•pandas
•matplotlib
•seaborn
•plotly
•sciPy

NumPy: numeric python
-Package for scientific computing in python
-NumPy is Library that provides n-dimensional array objects.
-fast operation on Arrays including logical ,shape manipulation,sorting,selecting,discrete mathematics,Fourier Transforms



In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
b= np.array([1,2,3.5,'dev',79])
print(b)
print(type(b))
print(a.dtype)
print(b.dtype)
      

['1' '2' '3.5' 'dev' '79']
<class 'numpy.ndarray'>
int64
<U32


<h1>reshaping</h1>
-as long as the elements required for reshaping are equal in both shapes
-E.g we can reshape an 8 elements 1d array into 4 elements in 2 rows 2d array but we can not reswhape it into a 3elements rows 2d array


In [8]:
import numpy as np
a=np.array([2,3,4,5,6,8,3,5,6])
na=a.reshape(3,3)
print(na)

[[2 3 4]
 [5 6 8]
 [3 5 6]]


<h1> Resizing </h1>
The resize() function is used to create a new array with the specified shape
If the new array is larger than the original array,then the new array is filled with repeated copies of a.

In [13]:
import numpy as np
arr=np.array([[1,2],[5,6]])
na=np.resize(arr,(3,2))
print(na)

[[1 2]
 [5 6]
 [1 2]]


<h1>difference</h1>
reshape does not change the original array but only returns the changed array.
whereas the resize() method returns nothing and directly changes the original array.

In [1]:
import numpy as np
cs=np.array([1,2,3,4,5,6])
print("Original")
print(cs)
print("changed")
print(cs.resize(2,3))
print("reshape")
print(cs.reshape(3,2))
print(cs)

Original
[1 2 3 4 5 6]
changed
None
reshape
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [20]:
#creating a 2d array
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
print(type(ar))
print(ar[:2,:2])
print(ar[::-1,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[1 2]
 [4 5]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


Attributes in numpy
•ndim:Provides dimensions in array
•size:Provides order of the matrix
•shape:provide order of matrix
•nbytes:No. of bytes occupied by an array
•itemsize: Bytes occupied by each elements
•dtype : give type of elements 

In [21]:
import numpy as np
a=np.array([1,2,3,4,5,6])
b=np.array([[1,2,3],[2,3,4],[4,5,6]])
print(a)
print(b)
print(a.ndim)
print(b.ndim)
print(a.size)
print(b.size)
print(a.shape)
print(b.shape)


[1 2 3 4 5 6]
[[1 2 3]
 [2 3 4]
 [4 5 6]]
1
2
6
9
(6,)
(3, 3)


In [38]:
a=np.zeros((2,4),dtype='int16')
b=np.ones((3,4))
print(a)
print("\n",b)
x=np.full((3,4),10)
print("\n",x)
y=np.full((3,3),np.nan)
print("\n",y)
m=np.diag([10,20,30,40,50])
print("\n",m)
e=np.eye(5)
print("\n",e)

[[0 0 0 0]
 [0 0 0 0]]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]

 [[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]

 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


•Flatten: it creates 1d array from any nd array
•Ravel:it create 1d array from any nd array

#ravel is fasteer 

In [34]:
a=np.array([[1,2,3],[4,5,6],[5,6,7]])
b=a.ravel()
print(b)
c=a.flatten()
print(c)

[1 2 3 4 5 6 5 6 7]
[1 2 3 4 5 6 5 6 7]


In [35]:
#random array
d=np.random.rand(3,4)
print(d)


[[0.98490505 0.68847665 0.28447163 0.5349603 ]
 [0.58191546 0.33886466 0.3577414  0.1981104 ]
 [0.16806657 0.80749303 0.21895408 0.04863561]]


In [36]:
#random array
d=np.random.randint(-4,10,size=(2,3))
print(d)


[[-4  0  2]
 [ 9  4  7]]


In [39]:
#random array
d=np.arange(10,30)
print(d)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [42]:
a=np.array([1,2,3,4,5,6])
print(np.tan(a))

[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]


In [51]:
a=np.array([[3,4,5],[4,6,7],[7,8,9]])
b=np.array([[4,5,5],[4,62,7],[72,2,9]])
print(a)
a.transpose()
print(np.trace(a))
print(a+b)
print(a.dot(b))
print(a@b)
print(np.matmul(a,b))
print(np.linalg.det(a))
print(np.linalg.det(b))
print(np.linalg.inv(a))
print(np.linalg.inv(b))


[[3 4 5]
 [4 6 7]
 [7 8 9]]
18
[[ 7  9 10]
 [ 8 68 14]
 [79 10 18]]
[[388 273  88]
 [544 406 125]
 [708 549 172]]
[[388 273  88]
 [544 406 125]
 [708 549 172]]
[[388 273  88]
 [544 406 125]
 [708 549 172]]
-4.000000000000004
-17763.99999999999
[[ 0.5  -1.    0.5 ]
 [-3.25  2.    0.25]
 [ 2.5  -1.   -0.5 ]]
[[-0.03062373  0.00197028  0.01548075]
 [-0.02634542  0.01823914  0.00045035]
 [ 0.2508444  -0.01981536 -0.01283495]]
